# Generated by Django 4.2.4 on 2023-08-26 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_teacherprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentProfile",
            new_name="Student_Profile",
        ),
    ]
