# Generated by Django 4.2.4 on 2023-08-26 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0006_rename_studentprofile_student_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student_Profile",
            new_name="StudentProfile",
        ),
    ]
